/**
 * export-engine.js
 * 專業格式匯出引擎
 * 支援：PNG / SVG / ASE / ACO / JSON (Design Tokens) / CSS 變數
 * 依賴：color-convert.js
 */

'use strict';

const ExportEngine = (() => {

  // ─────────────────────────────────────────────
  // 工具：觸發瀏覽器下載
  // ─────────────────────────────────────────────

  function downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 1000);
  }

  function downloadText(text, filename, mimeType = 'text/plain') {
    downloadBlob(new Blob([text], { type: mimeType }), filename);
  }

  function timestamp() {
    return new Date().toISOString().slice(0, 10);
  }

  // ─────────────────────────────────────────────
  // PNG 匯出
  // ─────────────────────────────────────────────

  /**
   * 將 Canvas 匯出為 PNG
   * @param {HTMLCanvasElement} canvas
   * @param {string} [filename]
   */
  function exportPng(canvas, filename = `palette-${timestamp()}.png`) {
    canvas.toBlob(blob => {
      if (blob) downloadBlob(blob, filename);
    }, 'image/png');
  }

  // ─────────────────────────────────────────────
  // SVG 向量色票卡匯出
  // ─────────────────────────────────────────────

  /**
   * 生成 SVG 向量色票卡
   * @param {string[]} palette HEX 陣列
   * @param {object} opts
   * @returns {string} SVG 字串
   */
  function buildSvg(palette, opts = {}) {
    const { gap = 4, radius = 0, showHex = false, swatchH = 80 } = opts;
    const count  = palette.length;
    const totalW = 800;
    const totalGap = gap * (count - 1);
    const swatchW = (totalW - totalGap) / count;
    const labelH  = showHex ? 24 : 0;
    const totalH  = swatchH + labelH;

    const rects = palette.map((hex, i) => {
      const x = i * (swatchW + gap);
      const textColor = ColorConvert.contrastColor(hex);
      const label = showHex
        ? `<text x="${x + swatchW / 2}" y="${swatchH + 16}"
              font-family="JetBrains Mono, monospace" font-size="11"
              fill="#aaa" text-anchor="middle">${hex.toUpperCase()}</text>`
        : '';
      return `
  <rect x="${x.toFixed(2)}" y="0" width="${swatchW.toFixed(2)}" height="${swatchH}"
        fill="${hex}" rx="${radius}" ry="${radius}"/>
  ${label}`;
    }).join('');

    return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 ${totalW} ${totalH}"
     width="${totalW}" height="${totalH}">
  <title>Color Palette — Image Palette Studio</title>
  <desc>Generated by Image Palette Studio</desc>
  <rect width="${totalW}" height="${totalH}" fill="#111"/>
  ${rects}
</svg>`;
  }

  function exportSvg(palette, opts = {}, filename = `palette-${timestamp()}.svg`) {
    const svg = buildSvg(palette, opts);
    downloadText(svg, filename, 'image/svg+xml');
  }

  // ─────────────────────────────────────────────
  // ASE (Adobe Swatch Exchange) 匯出
  // ─────────────────────────────────────────────

  /**
   * 生成 .ase 二進位 Buffer
   * ASE 格式規格：
   *  Header: 4 bytes "ASEF" + version 1.0 (2+2) + block count (4)
   *  Per color: block type 0x0001 (2) + block length (4) +
   *             name length (2) + name UTF-16 + "RGB " (4) + RGB floats (12) + type (2)
   */
  function buildAseBuffer(palette, names = []) {
    const colors = palette.map((hex, i) => {
      const { r, g, b } = ColorConvert.hexToRgb(hex);
      return {
        name: names[i] || hex.toUpperCase(),
        r: r / 255, g: g / 255, b: b / 255,
      };
    });

    // 計算 buffer 大小
    let size = 12; // header
    const colorBlocks = colors.map(c => {
      const nameUtf16Len = (c.name.length + 1) * 2; // +1 for null terminator
      return { ...c, nameUtf16Len, blockLen: 2 + nameUtf16Len + 4 + 12 + 2 };
    });
    colorBlocks.forEach(b => { size += 2 + 4 + b.blockLen; });

    const buf = new ArrayBuffer(size);
    const view = new DataView(buf);
    let offset = 0;

    const writeUint8  = v => { view.setUint8(offset++, v); };
    const writeUint16 = v => { view.setUint16(offset, v, false); offset += 2; };
    const writeUint32 = v => { view.setUint32(offset, v, false); offset += 4; };
    const writeFloat  = v => { view.setFloat32(offset, v, false); offset += 4; };
    const writeChar   = c => writeUint8(c.charCodeAt(0));

    // Header
    'ASEF'.split('').forEach(writeChar);
    writeUint16(1); writeUint16(0);   // version 1.0
    writeUint32(colors.length);       // block count

    // Color blocks
    colorBlocks.forEach(c => {
      writeUint16(0x0001);            // block type: color
      writeUint32(c.blockLen);        // block length

      // Color name (UTF-16 BE with null terminator)
      writeUint16(c.name.length + 1);
      for (let i = 0; i < c.name.length; i++) {
        writeUint16(c.name.charCodeAt(i));
      }
      writeUint16(0x0000);            // null terminator

      // Color model: "RGB "
      'RGB '.split('').forEach(writeChar);

      // RGB float values
      writeFloat(c.r);
      writeFloat(c.g);
      writeFloat(c.b);

      // Color type: 0 = Global
      writeUint16(0);
    });

    return buf;
  }

  function exportAse(palette, names = [], filename = `palette-${timestamp()}.ase`) {
    const buf = buildAseBuffer(palette, names);
    downloadBlob(new Blob([buf], { type: 'application/octet-stream' }), filename);
  }

  // ─────────────────────────────────────────────
  // ACO (Adobe Photoshop Color) 匯出
  // ─────────────────────────────────────────────

  /**
   * 生成 .aco buffer（Version 1 + Version 2）
   * Version 1: colorSpace(2) + 4x uint16 + padding(2)
   * Version 2: same + name length(4) + name UTF-16
   */
  function buildAcoBuffer(palette, names = []) {
    const colors = palette.map((hex, i) => {
      const { r, g, b } = ColorConvert.hexToRgb(hex);
      return { r, g, b, name: names[i] || hex.toUpperCase() };
    });

    const count = colors.length;
    // V1: 4 + count * 10
    // V2: 4 + count * (10 + 4 + (name.length+1)*2)
    let v2Extra = colors.reduce((s, c) => s + 4 + (c.name.length + 1) * 2, 0);
    const buf = new ArrayBuffer(4 + count * 10 + 4 + count * 10 + v2Extra);
    const view = new DataView(buf);
    let offset = 0;

    const w16 = v => { view.setUint16(offset, v, false); offset += 2; };
    const w32 = v => { view.setUint32(offset, v, false); offset += 4; };

    // === Version 1 ===
    w16(1);       // version
    w16(count);   // count
    colors.forEach(c => {
      w16(0);                           // colorSpace: 0 = RGB
      w16(Math.round(c.r / 255 * 65535));
      w16(Math.round(c.g / 255 * 65535));
      w16(Math.round(c.b / 255 * 65535));
      w16(0);                           // padding
    });

    // === Version 2 ===
    w16(2);       // version
    w16(count);   // count
    colors.forEach(c => {
      w16(0);
      w16(Math.round(c.r / 255 * 65535));
      w16(Math.round(c.g / 255 * 65535));
      w16(Math.round(c.b / 255 * 65535));
      w16(0);
      // Name
      w32(c.name.length + 1);
      for (let i = 0; i < c.name.length; i++) w16(c.name.charCodeAt(i));
      w16(0); // null terminator
    });

    return buf;
  }

  function exportAco(palette, names = [], filename = `palette-${timestamp()}.aco`) {
    const buf = buildAcoBuffer(palette, names);
    downloadBlob(new Blob([buf], { type: 'application/octet-stream' }), filename);
  }

  // ─────────────────────────────────────────────
  // JSON Design Tokens 匯出 (W3C Format)
  // ─────────────────────────────────────────────

  function buildDesignTokens(palette, names = []) {
    const tokens = {};
    palette.forEach((hex, i) => {
      const key = names[i]
        ? names[i].toLowerCase().replace(/\s+/g, '-')
        : `color-${i + 1}`;
      const rgb  = ColorConvert.hexToRgb(hex);
      const hsl  = ColorConvert.rgbToHsl(rgb.r, rgb.g, rgb.b);
      tokens[key] = {
        $value: hex.toUpperCase(),
        $type:  'color',
        $extensions: {
          'studio.image-palette': {
            rgb:  `rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`,
            hsl:  `hsl(${Math.round(hsl.h)}, ${hsl.s.toFixed(1)}%, ${hsl.l.toFixed(1)}%)`,
            index: i,
          }
        }
      };
    });
    return { 'image-palette-studio': tokens };
  }

  function exportJson(palette, names = [], filename = `palette-tokens-${timestamp()}.json`) {
    const tokens = buildDesignTokens(palette, names);
    downloadText(JSON.stringify(tokens, null, 2), filename, 'application/json');
  }

  // ─────────────────────────────────────────────
  // CSS 變數匯出
  // ─────────────────────────────────────────────

  function buildCssVariables(palette, names = []) {
    const lines = [
      `/* Image Palette Studio — Generated ${timestamp()} */`,
      ':root {',
    ];
    palette.forEach((hex, i) => {
      const slug = names[i]
        ? names[i].toLowerCase().replace(/\s+/g, '-')
        : `color-${i + 1}`;
      const rgb = ColorConvert.hexToRgb(hex);
      const hsl = ColorConvert.rgbToHsl(rgb.r, rgb.g, rgb.b);
      lines.push(`  --${slug}: ${hex.toUpperCase()};`);
      lines.push(`  --${slug}-rgb: ${rgb.r}, ${rgb.g}, ${rgb.b};`);
      lines.push(`  --${slug}-hsl: ${Math.round(hsl.h)}, ${hsl.s.toFixed(1)}%, ${hsl.l.toFixed(1)}%;`);
    });
    lines.push('}');
    return lines.join('\n');
  }

  function exportCss(palette, names = [], filename = `palette-${timestamp()}.css`) {
    downloadText(buildCssVariables(palette, names), filename, 'text/css');
  }

  // ─────────────────────────────────────────────
  // 統一匯出入口
  // ─────────────────────────────────────────────

  /**
   * @param {string} format 'png'|'svg'|'ase'|'aco'|'json'|'css'
   * @param {HTMLCanvasElement|null} canvas
   * @param {string[]} palette
   * @param {string[]} names
   * @param {object} opts
   */
  function exportAs(format, canvas, palette, names = [], opts = {}) {
    switch (format) {
      case 'png':  exportPng(canvas); break;
      case 'svg':  exportSvg(palette, opts); break;
      case 'ase':  exportAse(palette, names); break;
      case 'aco':  exportAco(palette, names); break;
      case 'json': exportJson(palette, names); break;
      case 'css':  exportCss(palette, names); break;
      default: console.warn('[ExportEngine] 未知格式:', format);
    }
  }

  // ─────────────────────────────────────────────
  // 公開 API
  // ─────────────────────────────────────────────
  return {
    exportAs,
    exportPng,
    exportSvg,
    exportAse,
    exportAco,
    exportJson,
    exportCss,
    buildSvg,
    buildDesignTokens,
    buildCssVariables,
    buildAseBuffer,
    buildAcoBuffer,
  };

})();

window.ExportEngine = ExportEngine;
